name: Pipleline
on: [push, pull_request]

jobs:
    test_robot:
        runs-on: ubuntu-latest

        steps:
            - name: Copiar os arquivos do repositório
              uses: actions/checkout@v4.1.4

            - name: Instalar o python
              uses: actions/setup-python@v5
              with:
                python-version: '3.11' 
