name: Pipleline
on: [push, pull_request]

jobs:
    test_robot:
        runs-on: ubuntu-latest
        permissions: write-all

        steps:
            - name: Copiar os arquivos do projeto
              uses: actions/checkout@v4.1.4

            - name: Instalar o python
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'

            - name: Instalar o NodeJS
              uses: actions/setup-node@v4
                
            - name: Instalar as Bibliotecas do projeto
              run: |
                  python -m pip install --upgrade pip
                  pip install -U -r requirements.txt
                  sudo npm install @playwright/test
                  sudo npx playwright install-deps
                  rfbrowser init


            - name: Execução dos testes 
              run: |
                 robot -d ./results -v HEADLESS:true tests

            - name: Upload das evidências de teste
              if: always()
              uses: actions/upload-artifact@v3
              with: 
                  name: resultado dos testes
                  path: ./results
                  if-no-files-found: ignore
                  retention-days: 2

            - name: Resultado do Download
              if: always()
              uses: actions/download-artifact@v1
              with:
                name: resultado dos testes

            - name: Enviar relatorio
              if: always()
              uses: joonvena/robotframework-reporter-action@v2.4
              with:
                report_path: resultado dos testes
                gh_access_token: ${{ secrets.GITHUB_TOKEN }}
                show_passed_tests: false
                

