name: Pipleline
on: [push, pull_request]

jobs:
    test_robot:
        runs-on: ubuntu-latest

        steps:
            - name: Copiar os arquivos do repositório
              uses: actions/checkout@v4.1.4
